name: publish

on:
  pull_request: 
    branches:
      - main

jobs:
  dotnet-security:
    uses: vestfoldfylke/shared/.github/workflows/dotnet-security.yml@7dd74fa211cea03c1a9844f0550378a52dabab5a # 1.3.0
    with:
      dotnet_version: "10.0.x"
      framework_version: "net10.0"
